Repository qopnetlabs/qopnet-platform, pull requests merged in 2021-11, with the labels that each got.

#136 QOP-228 Improve supplier page information
  apps/qopnet-commerce/pages/[supplierParam]/index.tsx
  apps/qopnet-commerce/pages/[supplierParam]/orders/index.tsx
Labels: enhancement

#137 QOP-235 Upload proof of payment receipt image to Supabase Storage
  apps/qopnet-commerce/components/business-order.tsx
  apps/qopnet-commerce/components/index.ts
  apps/qopnet-commerce/pages/dashboard/orders/index.tsx
Labels: enhancement

#139 QOP-249 Remove Orders breadcrumb in checkout process
  apps/qopnet-commerce/components/breadcrumb.tsx
  apps/qopnet-commerce/pages/cart/payment/index.tsx
Labels: bug

#138 QOP-250 Only show Detail Transfer popup on Manual Tranfer
  apps/qopnet-commerce/pages/cart/payment/index.tsx
Labels: bug

#142 QOP-182 Commerce product description display new line
  apps/qopnet-commerce/components/business-order.tsx
  libs/qopnet-ui/src/lib/supplier-product/supplier-product.tsx
Labels: bug, enhancement

#141 QOP-257 Payment endpoints VA Permata
  apps/qopnet-api/src/app/business/orders/middleware.ts
  apps/qopnet-api/src/app/payments/va/index.ts
  apps/qopnet-api/src/app/payments/va/middleware.ts
  apps/qopnet-api/src/main.ts
  prisma/data/payments-methods.json
  prisma/data/profiles.json
  prisma/migrations/20211102144703_virtual_account_number/migration.sql
  prisma/schema.prisma
Labels: enhancement

#145 QOP-260 Backup production database, then restore with Prisma migrate and seed
  prisma/data/addresses.json
  prisma/data/profiles-dev.json
  prisma/data/profiles-prd.json
  prisma/data/profiles-stg.json
  prisma/data/profiles.json
  prisma/data/supplier-products-ardena.json
  prisma/data/supplier-products-qopnet.json
  prisma/data/suppliers.json
  prisma/data/users-dev.json
  prisma/data/users-prd.json
  prisma/data/users-stg.json
  prisma/data/users.json
  prisma/migrations/20210804004509_init/migration.sql
  prisma/migrations/20210804100513_promo_provider_submission/migration.sql
  prisma/migrations/20210810142128_create_table_promo_employee/migration.sql
  prisma/migrations/20210811154612_courier_vehicle/migration.sql
  prisma/migrations/20210811160601_add_missing_fields/migration.sql
  prisma/migrations/20210811162248_try_referential_actions/migration.sql
  prisma/migrations/20210811163528_payment_method_record/migration.sql
  prisma/migrations/20210811174845_update_payment_category/migration.sql
  prisma/migrations/20210812021834_create_promo_employer/migration.sql
  prisma/migrations/20210812030735_change_promo_employers/migration.sql
  prisma/migrations/20210812045815_change_employer_id/migration.sql
  prisma/migrations/20210813050438_birth_date_to_date/migration.sql
  prisma/migrations/20210816070450_payment_record/migration.sql
  prisma/migrations/20210816085058_payment_method_account/migration.sql
  prisma/migrations/20210921135907_rename_index/migration.sql
  prisma/migrations/20211102101105_rename_index/migration.sql
  prisma/migrations/20211102144703_virtual_account_number/migration.sql
  prisma/migrations/20211106080125_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement

#144 QOP-258 Single business order page after checkout process with payment section
  apps/qopnet-commerce/components/breadcrumb.tsx
  apps/qopnet-commerce/components/business-order.tsx
  apps/qopnet-commerce/pages/dashboard/orders/[businessOrderParam]/index.tsx
  apps/qopnet-commerce/pages/dashboard/orders/index.tsx
Labels: enhancement

#147 QOP-263 Prevent process user order with VA if there are unpaid order with VA
  apps/qopnet-api/src/app/business/orders/middleware.ts
Labels: enhancement

#149 QOP-255 GET all BusinessOrderItem by Supplier that already paid
  apps/qopnet-api/src/app/business/orders/index.ts
  apps/qopnet-api/src/app/business/orders/middleware.ts
Labels: enhancement

#150 QOP-265 Payment instruction for virtual account
  apps/qopnet-commerce/components/business-order.tsx
  apps/qopnet-commerce/components/index.ts
  apps/qopnet-commerce/components/simple-business-order.tsx
  apps/qopnet-commerce/pages/dashboard/orders/index.tsx
  package-lock.json
  package.json
Labels: enhancement

#152 QOP-269 Add more detail response get all paid business order items by supplier
  apps/qopnet-api/src/app/business/orders/middleware.ts
Labels: enhancement

#154 QOP-270 Courier options only deliveree and kurir toko sendiri
  prisma/data/couriers.json
  prisma/migrations/20211111045109_create_status_to_business_order_item/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: enhancement

#153 QOP-245 BusinessOrderItemStatus for each BusinessOderItem
  .gitignore
  apps/qopnet-api/src/app/business/orders/middleware.ts
  package-lock.json
  package.json
  prisma/migrations/20211111045109_create_status_to_business_order_item/migration.sql
  prisma/migrations/20211112181615_init/migration.sql
  prisma/schema.prisma
  prisma/triggers/copy-users-function.sql
Labels: bug, enhancement

#155 QOP-273 Patch business order item status
  apps/qopnet-api/src/app/business/orders/index.ts
  apps/qopnet-api/src/app/business/orders/middleware.ts
Labels: enhancement

#156 QOP-267 API courier options per business order item
  apps/qopnet-api/src/app/business/orders/index.ts
  apps/qopnet-api/src/app/business/orders/middleware.ts
  package.json
  prisma/migrations/20211112190202_init/migration.sql
  prisma/migrations/20211112191226_courier_vehicles/migration.sql
  prisma/schema.prisma
Labels: bug, enhancement

#157 QOP-223 Update Supplier Product button + form page
  apps/qopnet-commerce/components/business-order.tsx
  apps/qopnet-commerce/components/supplier-product.tsx
  apps/qopnet-commerce/pages/[supplierParam]/[supplierProductParam]/edit-supplier-product/index.tsx
  apps/qopnet-commerce/pages/[supplierParam]/create-supplier-product/index.tsx
  libs/qopnet-ui/src/lib/supplier-product/supplier-product.tsx
Labels: bug, enhancement

#158 QOP-266 Show proof images in detail pesanan
  apps/qopnet-api/src/app/business/orders/middleware.ts
  apps/qopnet-api/src/app/payments/records/middleware.ts
  apps/qopnet-commerce/components/business-order.tsx
  apps/qopnet-commerce/pages/[supplierParam]/orders/index.tsx
  package-lock.json
Labels: bug

#159 QOP-274 API get one paid business order item by supplier
  apps/qopnet-api/src/app/business/orders/index.ts
  apps/qopnet-api/src/app/business/orders/middleware.ts
Labels: enhancement

#161 QOP-279 Supplier product can manage couriers
  apps/qopnet-api/src/app/suppliers/middleware.ts
  prisma/migrations/20211114064510_m2m_couriers_on_supplier_products/migration.sql
  prisma/schema.prisma
Labels: enhancement

#162 QOP-280 Seed couriers into supplier products
  apps/qopnet-api/src/app/suppliers/middleware.ts
  libs/shared-types/src/lib/shared-types.ts
  package.json
  prisma/data/supplier-products-anekabusa.json
  prisma/seed.ts
Labels: enhancement

#160 Fix optimisic quantity change in cart page
  apps/qopnet-commerce/pages/cart/index.tsx
Labels: bug

#163 QOP-281 Commerce create supplier product form with couriers
  apps/qopnet-api/src/app/suppliers/products/middleware.ts
  apps/qopnet-commerce/components/supplier-product.tsx
  apps/qopnet-commerce/pages/[supplierParam]/[supplierProductParam]/edit-supplier-product/index.tsx
Labels: bug, enhancement

#165 QOP-278 API sort by desc updatedAt
  apps/qopnet-api/src/app/addresses/middleware.ts
  apps/qopnet-api/src/app/business/orders/middleware.ts
  apps/qopnet-api/src/app/couriers/middleware.ts
  apps/qopnet-api/src/app/couriers/vehicles/middleware.ts
  apps/qopnet-api/src/app/merchants/middleware.ts
  apps/qopnet-api/src/app/payments/records/middleware.ts
  apps/qopnet-api/src/app/promos/submissions/middleware.ts
  apps/qopnet-api/src/app/suppliers/middleware.ts
  apps/qopnet-api/src/app/users/middleware.ts
Labels: enhancement, automerge

#166 QOP-283 Fix Supplier's address in seed data
  prisma/data/addresses.json
  prisma/seed.ts
Labels: bug, enhancement, automerge

#167 QOP-276 Redesign All Paid Business Order Item
  apps/qopnet-commerce/pages/[supplierParam]/orders/index.tsx
Labels: enhancement, automerge

#164 QOP 268: Commerce courier picker per product in cart/shipment page
  apps/qopnet-api/src/app/business/orders/middleware.ts
  apps/qopnet-commerce/components/supplier-product.tsx
  apps/qopnet-commerce/pages/cart/shipment/index.tsx
Labels: enhancement, automerge
